### ISSUE TITLE
Add New folders to Repository

### ISSUE THREAD

**Issue by Dustin1230** [AzXeus/Ascension#18]
Create new folders in the github repository for the INI, INT, and other(README, Installation, etc.) files associated with Ascension, ModBridge, and Training Roulette Plus.

**Comment by Dustin1230** [comment]
Done, folder structure established.

**Comment by AzXeus** [comment]
[f71d2eb](https://github.com/AzXeus/Ascension/commit/f71d2eb01732bbcece49360fef7d56aa13638e89)
